version: "1.0"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db:/data/db
  app:
    container_name: app
    depends_on:
      - mongo
    build: ./
    restart: unless-stopped
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  db:
  caddy_data:
  caddy_config:
